### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by JennLuhman** [DaveLuhman/toolkeeper#216]
Remove the serial number column and add the service assignment name instead

**Comment by DaveLuhman** [comment]
# Reopening issue

New dashboard setup shows 0 checked in tools, when SA tool count shows 1241 assigned to SHOP (00022))

**Comment by DaveLuhman** [comment]
Found coercion/type collision on line 99 in tool.js middleware file.

strict comparison operator causes SA._id to fail lookup on populated reference document on tool object. 

on line 88, an array of just the _id values is initd. If we skip that and use the full documents for comparison, strict comparison should evaluate properly.
