### ISSUE TITLE
import selection buttons

### ISSUE THREAD

**Issue by SquirrelCall** [DaveLuhman/toolkeeper#297]
Could you make the import category selection buttons more obvious? it took me a couple failed attempts to figure out that was the issue. 

![{8D6D1637-3814-4272-ADBA-BBA2F5C6FC05}](https://github.com/user-attachments/assets/e19d98ed-eba5-442a-8ea6-7225f31b33d8)

**Comment by DaveLuhman** [comment]
The radio button for each option has been increased substantially in size.  This should make it clearer that one needs to be selected.  It should be noted that one cannot submit the form without picking an option.
